version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - checkout
            - restore_cache:
               key: npm-cache-v1-{{ checksum "package.json" }}
            - run:
                name: Install Dependencies
              command: yarn install
            - save_cache:
              key: npm-cache-v1-{{ checksum "package.json" }}
              paths:
            - node_modules
            - run:
              name: Run Tests
               command: 
                mkdir -p ./test-results/junit
                yarn test --ci --reporters=jest-junit
            - store_artifacts:
              path: ./test-results/junit
          - store_test_results:
              path: ./test-results
workflows:
    build-and-test:
      jobs:
        - build-and-test